services:
  task_optimizer:
    build:
      context: ./task_optimizer
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - 8080:8080
    volumes:
      - logs:/logs
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./o11y/prometheus:/etc/prometheus
      - prom_data:/prometheus
  loki:
    image: grafana/loki
    command:
      - '--config.file=/etc/loki/local-config.yaml'
    ports:
      - 3100:3100
    restart: unless-stopped
    volumes:
      - loki_data:/loki
  promtail:
    image: grafana/promtail
    command:
      - '--config.file=/etc/promtail/config.yaml'
    depends_on:
      - loki
    volumes:
      - ./o11y/promtail:/etc/promtail
      - logs:/logs
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./o11y/grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
volumes:
  prom_data:
  loki_data:
  logs:
