{
 "title": "Task optimizer",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "BronKerbosch execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(task_optimizer_bron_kerbosch_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(task_optimizer_bron_kerbosch_duration_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    { "expression": "($A/$B)*1000", "type": "math" }
   ]
  },
  {
   "title": "Last executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{path=\"/tasks/execution\"} |= `\"request completed\"`"
    }
   ]
  },
  {
   "title": "Task list size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "task_optimizer_task_list_size{job=\"task_optimizer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Optimizer Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{host=\"task_optimizer\", level=\"error\"}"
    }
   ]
  }
 ]
}