server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: volume_logs
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: time
            method: method
            path: path
            status: status
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          method:
          path:
          status:
    static_configs:
      - labels:
          job: task_optimizer
          host: task_optimizer
          __path__: /logs/task_optimizer.log
